package com.chcraft.erd.utils;

import java.util.List;

import com.chcraft.erd.Entity;
import com.chcraft.erd.Relationship;

public class SimpleSQLFileGenerator implements SQLFileGenerator {
	private final static String ENTITY_TEMPLATE = "-- generated by SimpleSQLFileGenerator";
	private final static String RELATIONSHIP_TEMPLATE = "";

	public String generateFile(List<Entity> entities, List<Relationship> relationships) {
		StringBuilder sb = new StringBuilder();




		return sb.toString();
	}

	private String generateEntity(Entity entity) {
		StringBuilder sb = new StringBuilder();

		return sb.toString();
	}
}
